name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USER_NAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  # DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save k8s-1-26-3-do-0-blr1-1680764427709
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod