name: deploy-client

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USER_NAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: cd client && docker build -t 231615/ticketing-client .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker push 231615/ticketing-client
      - run: doctl kubernetes cluster kubeconfig save d1bb9489-3b0a-4889-ab87-bd34faf8d563
      - run: kubectl rollout restart deployment client-depl